### ISSUE TITLE
Factory test

### ISSUE THREAD

**Issue by megabyte2010** [jhiggason/lorawirelesstracker#1]
Great job. Do you have the factory test for 1.1? I can´t find it. Thank you.

**Comment by jhiggason** [comment]
You can find it under Getting Started and then Examples.  https://github.com/Heltec-Aaron-Lee/WiFi_Kit_series/tree/master/esp32/libraries/Heltec-Example/examples

Otherwise as long as you you get the correct arduino library installed in the IDE it will be in there as well.
