### ISSUE TITLE
Case modification?

### ISSUE THREAD

**Issue by kovar-ursa** [jhiggason/lorawirelesstracker#2]
I'm using the boards without the headers and with the flat LiPo batteries. The current bottom of the case is too deep and the battery rattles around.

Would it be possible to make a shorter lower part, possibly with a lip on the bottom to keep the battery from sliding?

I'm happy to make the modification myself if you want to share the CAD files.

Thank you.

**Comment by jhiggason** [comment]
Hey!  I didn't make the case...my neighbor did.  But he provided the onshape file you can find here: https://github.com/jhiggason/lorawirelesstracker/blob/main/3D%20Printed%20Case/README.md

If you make a different version let me know and I'll add it to the Readme.  👍

**Comment by kovar-ursa** [comment]
Greetings,

Thank you very much! I’ll let you know if I produce anything useful.

<Off topic comment removed.>

Cheers,

-David

**Comment by jhiggason** [comment]
Issue should be resolved.  Closing.
